import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Menu } from "antd";
import { useRouter } from "next/router";

const items = [
  { label: "item-1", key: "item-1" }, // 菜单项务必填写 key
  { label: "item-2", key: "item-2" },
  {
    label: "submenu",
    key: "submenu",
    children: [{ label: "submenu-item-1", key: "submenu-item-1" }],
  },
];

const Home: NextPage = () => {
  const { push } = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Menu
          items={items}
          mode={"horizontal"}
          theme={"dark"}
          defaultSelectedKeys={["item-1"]}
          onSelect={(info) => {
            push('/test/' + info.key);
          }}
        />
      </main>
    </div>
  );
};

export default Home;
